# Generated by Django 4.1.7 on 2023-03-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment_post_date_update_post_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
